[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_dapp = "H3Ksfne1kwnxp1tvc6Fi3xWjpzDiNgSn4BB3JodoAV2A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/.bin/jest --preset ts-jest"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
